apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: bryanl/websay
  newName: bryanl/websay
  newTag: tekton
- name: websay
  newName: bryanl/websay
  newTag: "12345"
commonLabels:
  app: websay-dev
